package com.cosmosgenx.cryptoshortscanner;

import android.Manifest;
import android.app.NotificationChannel;
import android.app.NotificationManager;
import android.app.PendingIntent;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.os.Build;
import androidx.core.app.ActivityCompat;
import androidx.core.app.NotificationCompat;
import androidx.core.app.NotificationManagerCompat;
import com.google.firebase.messaging.FirebaseMessagingService;
import com.google.firebase.messaging.RemoteMessage;

public class ScannerFirebaseMessagingService extends FirebaseMessagingService {
    private static final String CHANNEL="server_short_alerts";

    @Override public void onNewToken(String token) {
        super.onNewToken(token);
        BackendClient.registerDevice(this,token);
    }

    @Override public void onMessageReceived(RemoteMessage msg) {
        super.onMessageReceived(msg);
        createChannel();
        String symbol=msg.getData().get("symbol");
        String score=msg.getData().get("score");
        String action=msg.getData().get("action");
        String catalyst=msg.getData().get("catalyst");
        if(symbol==null) symbol="Short setup";
        String body=(score==null?"":score+"/100 • ")+(action==null?"":action)+(catalyst==null||catalyst.isEmpty()?"":" • "+catalyst);

        Intent open=new Intent(this,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP);
        PendingIntent pi=PendingIntent.getActivity(this,Math.abs(symbol.hashCode()),open,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);
        NotificationCompat.Builder b=new NotificationCompat.Builder(this,CHANNEL)
                .setSmallIcon(android.R.drawable.stat_notify_more)
                .setContentTitle("Server alert: "+symbol)
                .setContentText(body)
                .setStyle(new NotificationCompat.BigTextStyle().bigText(body))
                .setContentIntent(pi).setAutoCancel(true).setPriority(NotificationCompat.PRIORITY_HIGH);
        if(Build.VERSION.SDK_INT>=33 && ActivityCompat.checkSelfPermission(this, Manifest.permission.POST_NOTIFICATIONS)!= PackageManager.PERMISSION_GRANTED) return;
        NotificationManagerCompat.from(this).notify(Math.abs((symbol+System.currentTimeMillis()/60000).hashCode()),b.build());
    }

    private void createChannel() {
        if(Build.VERSION.SDK_INT>=26) {
            NotificationChannel ch=new NotificationChannel(CHANNEL,"Server Short Alerts",NotificationManager.IMPORTANCE_HIGH);
            ch.setDescription("Push alerts generated by the server-side 24/7 scanner.");
            getSystemService(NotificationManager.class).createNotificationChannel(ch);
        }
    }
}
