package com.cosmosgenx.fomoconfluence;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity {
 LinearLayout feed; EditText minMc,maxMc,minTraders,window; final int FG=Color.rgb(236,245,255), MUTED=Color.rgb(160,177,197);
 @Override public void onCreate(Bundle b){super.onCreate(b); build();}
 TextView t(String s,int sp){TextView v=new TextView(this);v.setText(s);v.setTextColor(FG);v.setTextSize(sp);v.setPadding(0,5,0,5);return v;}
 EditText e(String hint,String val){EditText v=new EditText(this);v.setHint(hint);v.setText(val);v.setTextColor(FG);v.setHintTextColor(MUTED);v.setInputType(2);v.setBackgroundResource(com.cosmosgenx.fomoconfluence.R.drawable.glass);v.setPadding(18,8,18,8);return v;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(FG);b.setBackgroundResource(R.drawable.button);return b;}
 void build(){ScrollView sc=new ScrollView(this); LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(24,30,24,30);root.setBackgroundColor(Color.rgb(8,11,18)); sc.addView(root);
 TextView h=t("FOMO CONFLUENCE",28);h.setTypeface(null,1);root.addView(h); TextView status=t("● DEMO DATA  •  Live adapter not connected",13);status.setTextColor(Color.rgb(255,190,90));root.addView(status);
 LinearLayout filters=new LinearLayout(this);filters.setOrientation(LinearLayout.VERTICAL);filters.setBackgroundResource(R.drawable.glass);filters.setPadding(18,14,18,14);filters.addView(t("FILTERS",17));
 minMc=e("Min MC","5000");maxMc=e("Max MC","50000");minTraders=e("Minimum traders","3");window=e("Window (minutes)","15"); filters.addView(minMc);filters.addView(maxMc);filters.addView(minTraders);filters.addView(window);Button apply=btn("APPLY FILTERS");filters.addView(apply);root.addView(filters,new LinearLayout.LayoutParams(-1,-2));
 TextView sh=t("CONFLUENCE SIGNALS",20);sh.setPadding(0,24,0,8);root.addView(sh);feed=new LinearLayout(this);feed.setOrientation(LinearLayout.VERTICAL);root.addView(feed); apply.setOnClickListener(v->render());render();setContentView(sc); }
 void render(){feed.removeAllViews();addCard("$DEMO1","Solana","5 Top Traders","$23.4K","$31.8K","4m 17s","DemoContract111111111111111111111111111111");addCard("$DEMO2","Base","3 Top Traders","$41.2K","$47.6K","9m 02s","0x1111111111111111111111111111111111111111");}
 void addCard(String token,String chain,String traders,String entry,String current,String age,String ca){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setBackgroundResource(R.drawable.glass);c.setPadding(18,16,18,16);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,0,0,16);TextView title=t(token+"   •   "+chain,22);title.setTypeface(null,1);c.addView(title);c.addView(t(traders+"  |  formed in "+age,16));c.addView(t("Entry MC  "+entry+"     Current MC  "+current,15));TextView cv=t(ca,13);cv.setTextIsSelectable(true);cv.setTextColor(Color.rgb(159,231,255));c.addView(cv);LinearLayout actions=new LinearLayout(this);Button copy=btn("COPY CA");Button open=btn("OPEN FOMO");actions.addView(copy,new LinearLayout.LayoutParams(0,-2,1));actions.addView(open,new LinearLayout.LayoutParams(0,-2,1));copy.setOnClickListener(v->{((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("contract",ca));Toast.makeText(this,"Contract copied",Toast.LENGTH_SHORT).show();});open.setOnClickListener(v->{try{startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse("https://fomo.family/")));}catch(Exception x){Toast.makeText(this,"Unable to open FOMO",Toast.LENGTH_SHORT).show();}});c.addView(actions);feed.addView(c,cp);}
}
